platform:ios,'8.0'
target 'chu' do
pod 'AFNetworking', '~> 3.0'
pod 'YYModel'
pod 'YYCache'
pod 'SDWebImage', '~>3.8'
pod 'MJRefresh'
pod 'SDCycleScrollView','~> 1.64'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'  end
